openapi: 3.0.2
info:
    title: Beer Catalog API
    version: '0.9'
    description: An API for querying beer catalog of Acme Inc.
    contact:
        name: Laurent Broudoux
        url: 'http://github.com/lbroudoux'
        email: laurent.broudoux@gmail.com
    license:
        name: MIT License
        url: 'https://opensource.org/licenses/MIT'
paths:
    '/beer/{name}':
        get:
            tags:
                - beer
            responses:
                '200':
                    content:
                        'application/json':
                            schema:
                                $ref: '#/components/schemas/Beer'
                    description: Beer having requested name
            operationId: GetBeer
            summary: Get beer having name
            description: Get beer having name
        parameters:
            -
                name: name
                description: Name of beer to retrieve
                schema:
                    type: string
                in: path
                required: true
    '/beer/findByStatus/{status}':
        get:
            tags:
                - beer
            responses:
                '200':
                    content:
                        'application/json':
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Beer'
                    description: List of beers having requested status
            operationId: FindBeersByStatus
            summary: Get beers having status
            description: Get beers having status
        parameters:
            -
                name: status
                description: Status of beers to retrieve
                schema:
                    type: string
                in: path
                required: true
            -
                name: page
                description: Number of page to retrieve
                schema:
                    type: number
                in: query
    /beer:
        get:
            tags:
                - beer
            responses:
                '200':
                    content:
                        'application/json':
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Beer'
                            examples:
                                beers:
                                    value:
                                        -
                                            name: some text
                                            country: some text
                                            type: some text
                                            rating: 35.12
                                            status: some text
                                        -
                                            name: some text
                                            country: some text
                                            type: some text
                                            rating: 55.85
                                            status: some text
                                beers2:
                                    value:
                                        -
                                            name: exemplo 2
                                            country: some text
                                            type: some text
                                            rating: 61.19
                                            status: some text
                                        -
                                            name: some text
                                            country: some text
                                            type: some text
                                            rating: 77.11
                                            status: some text
                    description: Array of beers
            operationId: ListBeers
            summary: List beers within catalog
            description: List beers within catalog
        parameters:
            -
                name: page
                description: Number of page to retrieve
                schema:
                    type: number
                in: query
components:
    schemas:
        Beer:
            properties:
                name:
                    description: Name of Beer
                    type: string
                country:
                    description: Origin country of Beer
                    type: string
                type:
                    description: Type of Beer
                    type: string
                rating:
                    description: Rating from customers
                    type: number
                status:
                    description: Stock status
                    type: string
            example:
                name: some text
                country: some text
                type: some text
                rating: 75.88
                status: some text
    securitySchemes:
        api-key:
            type: apiKey
            name: api-key
            in: header
security:
    -
        api-key: []
tags:
    -
        name: beer
        description: Beer resource
